
{
    album:
    {
        album_type: 'album',
            artists: [[Object]],
                available_markets:
        ['AD',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'EC',
            'EE',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'IT',
            'JP',
            'LI',
            'LT',
            'LU',
            'LV',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'PA',
            'PE',
            'PH',
            'PL',
            'PT',
            'PY',
            'RO',
            'SE',
            'SG',
            'SK',
            'SV',
            'TH',
            'TR',
            'TW',
            'US',
            'UY',
            'VN',
            'ZA'],
            external_urls:
        { spotify: 'https://open.spotify.com/album/5qt11cWjSs5Gbqj2Wyfu38' },
        href: 'https://api.spotify.com/v1/albums/5qt11cWjSs5Gbqj2Wyfu38',
            id: '5qt11cWjSs5Gbqj2Wyfu38',
                images: [[Object], [Object], [Object]],
                    name: 'Enema Of The State',
                        release_date: '1999-01-01',
                            release_date_precision: 'day',
                                total_tracks: 12,
                                    type: 'album',
                                        uri: 'spotify:album:5qt11cWjSs5Gbqj2Wyfu38'
    },
    artists:
    [{
        external_urls: [Object],
        href: 'https://api.spotify.com/v1/artists/6FBDaR13swtiWwGhX1WQsP',
        id: '6FBDaR13swtiWwGhX1WQsP',
        name: 'blink-182',
        type: 'artist',
        uri: 'spotify:artist:6FBDaR13swtiWwGhX1WQsP'
    }],
        available_markets:
    ['AD',
        'AR',
        'AT',
        'AU',
        'BE',
        'BG',
        'BO',
        'BR',
        'CA',
        'CH',
        'CL',
        'CO',
        'CR',
        'CY',
        'CZ',
        'DE',
        'DK',
        'DO',
        'EC',
        'EE',
        'ES',
        'FI',
        'FR',
        'GB',
        'GR',
        'GT',
        'HK',
        'HN',
        'HU',
        'ID',
        'IE',
        'IL',
        'IN',
        'IS',
        'IT',
        'JP',
        'LI',
        'LT',
        'LU',
        'LV',
        'MC',
        'MT',
        'MX',
        'MY',
        'NI',
        'NL',
        'NO',
        'NZ',
        'PA',
        'PE',
        'PH',
        'PL',
        'PT',
        'PY',
        'RO',
        'SE',
        'SG',
        'SK',
        'SV',
        'TH',
        'TR',
        'TW',
        'US',
        'UY',
        'VN',
        'ZA'],
        disc_number: 1,
            duration_ms: 168000,
                explicit: false,
                    external_ids: { isrc: 'USMC19959123' },
    external_urls:
    { spotify: 'https://open.spotify.com/track/7yCPwWs66K8Ba5lFuU2bcx' },
    href: 'https://api.spotify.com/v1/tracks/7yCPwWs66K8Ba5lFuU2bcx',
        id: '7yCPwWs66K8Ba5lFuU2bcx',
            is_local: false,
                name: 'All The Small Things',
                    popularity: 80,
                        preview_url: null,
                            track_number: 8,
                                type: 'track',
                                    uri: 'spotify:track:7yCPwWs66K8Ba5lFuU2bcx'
}
personals - MBP: node personal$ 